steps:
# 1️⃣ Construcción de la imagen Docker desde la carpeta correcta
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'southamerica-east1-docker.pkg.dev/dqh-patrulla-360/dqh-artifact-registry-patrulla-360/app-flask',
    '-f', 'app-flask-gcp/Dockerfile',  # 📌 Ruta correcta al Dockerfile
    'app-flask-gcp'  # 📌 Contexto del build → donde está el código Flask
  ]

# 2️⃣ Subir la imagen a Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'southamerica-east1-docker.pkg.dev/dqh-patrulla-360/dqh-artifact-registry-patrulla-360/app-flask']

# 3️⃣ Verificar acceso al repositorio Artifact Registry
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'artifacts', 'repositories', 'describe',
    'dqh-artifact-registry-patrulla-360',
    '--location=southamerica-east1'
  ]

# 4️⃣ Listar imágenes en el repositorio (Opcional)
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'artifacts', 'docker', 'images', 'list',
    'southamerica-east1-docker.pkg.dev/dqh-patrulla-360/dqh-artifact-registry-patrulla-360'
  ]

# 5️⃣ Desplegar en Cloud Run con instancia mínima activa
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'run', 'deploy', 'app-flask',
      '--image', 'southamerica-east1-docker.pkg.dev/dqh-patrulla-360/dqh-artifact-registry-patrulla-360/app-flask',
      '--region', 'southamerica-east1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--min-instances', '1',
      '--memory', '256Mi',
      '--cpu', '0.5'
    ]

images:
- 'southamerica-east1-docker.pkg.dev/dqh-patrulla-360/dqh-artifact-registry-patrulla-360/app-flask'

options:
  logging: CLOUD_LOGGING_ONLY
